name: Linsight CI
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - develop
jobs:
  golangci:
    name: Golangci-Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"
        id: go
      - name: Make Mock files
        run: make gomock
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.51.2

  linux-test-with-coverage:
    name: Uint Test With Coverage(Linux)
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"
        id: go
      - name: Make Mock files
        run: make gomock
      - name: Test
        run: make test-without-lint
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
