name: PR Title Checker
on:
  pull_request_target:
    types:
      - opened
      - edited
      - reopened
      - synchronize
      - labeled
      - unlabeled
jobs:
  check:
    name: PR Title Checker
    runs-on: ubuntu-latest
    steps:
      - uses: thehanimo/pr-title-checker@v1.3.7
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          pass_on_octokit_error: false
          configuration_path: ".github/pr-title-checker-config.json"
